make: Add syntax to avoid yaml/jinja syntax errors

diff --git a/ansible/Makefile b/ansible/Makefile
--- a/ansible/Makefile
+++ b/ansible/Makefile
@@ -1,10 +1,12 @@
-# Makefile to handle pdf generation and syntax checks
+#
+# Makefile to handle ansible runs and syntax tests
 #
 #
 # Author: Sascha Girrulat <sascha@girrulat.de>
 #
 #
-# TODO: Add syntax checks for yml files
+
+all: syntax-checks ansible_with_key
 
 ansible_with_key:
 	    ansible-playbook -i inventory site.yml --vault-password-file=.vault-password -u root
@@ -12,4 +14,37 @@ ansible_with_key:
 ansible_with_password:
 	    ansible-playbook -i inventory site.yml --vault-password-file=.vault-password -u root -k
 
-ansible: ansible_with_password
+ansible: syntax-checks ansible_with_password
+
+syntax-checks: check-yaml check-jinja
+
+check-yaml:
+	for f in $$(find host_vars/ group_vars/ -regextype posix-egrep -type f -regex '[^.]+'); do \
+	  python -c "import yaml; yaml.load(open('$$f'))"; \
+	done
+
+	for f in $$(find . -name '*.yml'); do \
+	  python -c "import yaml; yaml.load(open('$$f'))"; \
+	done
+
+check-jinja:
+	for f in $$(find host_vars/ group_vars/ -regextype posix-egrep -type f -regex '[^.]+'); do \
+	  python -c "import jinja2; \
+	    e=jinja2.Environment(loader=jinja2.FileSystemLoader('./')); \
+	    e.filters['ipaddr'] = func=lambda:None; \
+	    e.get_template('$$f')"; \
+	  if [ $$? -ne 0 ]; then \
+	    echo "Syntax Error in file: $$f."; \
+	  fi; \
+	done
+
+	for f in $$(find . -regextype posix-egrep -type f -regex '.*j2'); do \
+	  python -c "import jinja2; \
+	    e=jinja2.Environment(loader=jinja2.FileSystemLoader('./')); \
+	    e.filters['ipaddr'] = func=lambda:None; \
+	    e.get_template('$$f')"; \
+	  if [ $$? -ne 0 ]; then \
+	    echo "Syntax Error in file: $$f."; \
+	  fi; \
+	done
+
